export const TOGGLE_APPLICATIONS_MENU = 'TOGGLE_APPLICATIONS_MENU';
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';
export const CHANGE_SHOWN_PRODUCT_MENU_ID = 'CHANGE_SHOWN_PRODUCT_MENU_ID';
export const CHANGE_PRODUCT_ID = 'CHANGE_PRODUCT_ID';
export const CHANGE_APPLICATION_ID = 'CHANGE_APPLICATION_ID';
