/*
 VISIBILITY
 */
export const TOGGLE_APPLICATIONS_MENU = 'TOGGLE_APPLICATIONS_MENU';
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';
export const TOGGLE_BUSINESS_PARTNER_MENU = 'TOGGLE_BUSINESS_PARTNER_MENU';
export const SHOW_BUSINESS_PARTNER_MENU = 'SHOW_BUSINESS_PARTNER_MENU';
export const HIDE_BUSINESS_PARTNER_MENU = 'HIDE_BUSINESS_PARTNER_MENU';
export const CHANGE_SELECTED_PRODUCT = 'CHANGE_SELECTED_PRODUCT';
export const RESET_SELECTED_PRODUCT = 'RESET_SELECTED_PRODUCT';

/*
 NAVIGATION
 */
export const CHANGE_CURRENT_PRODUCT = 'CHANGE_CURRENT_PRODUCT';
export const CHANGE_CURRENT_APPLICATION = 'CHANGE_CURRENT_APPLICATION';
export const CHANGE_CURRENT_BUSINESS_PARTNER = 'CHANGE_CURRENT_BUSINESS_PARTNER';
export const RESET_CURRENT_PRODUCT = 'RESET_CURRENT_PRODUCT';
export const RESET_CURRENT_APPLICATION = 'RESET_CURRENT_APPLICATION';
export const RESET_CURRENT_BUSINESS_PARTNER = 'RESET_CURRENT_BUSINESS_PARTNER';

/*
 BUSINESS PARTNERS
 */
export const UPDATE_ACCESSIBLE_BUSINESS_PARTNERS = 'UPDATE_ACCESSIBLE_BUSINESS_PARTNERS';
export const UPDATE_LAST_ACCESSED_BUSINESS_PARTNERS = 'UPDATE_LAST_ACCESSED_BUSINESS_PARTNERS';
export const UPDATE_BUSINESS_PARTNER_SEARCH_RESULTS = 'UPDATE_BUSINESS_PARTNER_SEARCH_RESULTS';
