export const TOGGLE_APPLICATIONS_MENU = 'TOGGLE_APPLICATIONS_MENU';
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';
export const CHANGE_SELECTED_PRODUCT_ID = 'CHANGE_SELECTED_PRODUCT_ID';
export const CHANGE_CURRENT_PRODUCT = 'CHANGE_CURRENT_PRODUCT';
export const CHANGE_CURRENT_APPLICATION = 'CHANGE_CURRENT_APPLICATION';
export const CHANGE_CURRENT_BUSINESS_PARTNER = 'CHANGE_CURRENT_BUSINESS_PARTNER';
export const TOGGLE_BUSINESS_PARTNER_MENU = 'TOGGLE_BUSINESS_PARTNER_MENU';
